apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "node13"
  annotations:
    humanitec.com/orgId: "htc-demo-41"
    humanitec.com/appId: "node13"
    quay.io/repository-slug: "quayadmin/node13"
    backstage.io/kubernetes-id: node13
    backstage.io/source-location: url:https://github.com/luizfaorg/node13
    github.com/project-slug: luizfaorg/node13
  tags:
    - node
    - humanitec
spec:
  type: service
  owner: "user1"
  lifecycle: experimental
  providesApis:
    - "node13"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "node13"
spec:
  type: openapi
  lifecycle: experimental
  owner: "user1"
  definition:
    $text: ./openapi.yaml
